### ISSUE TITLE
[bug] the bot does not seem to properly escape markdown symbols

### ISSUE THREAD

**Issue by RememberTheAir** [Nukesor/ultimate-poll-bot#22]
**Steps to reproduce**:
1. create a poll
2. send as title/option a string containing a markdown character

I've had a look at the sourcecode and it seems that most of the texts are sent using "markdown" as parse mode. Unfortunately, Telegram's markdown parsing makes use of symbols that are commonly used by people (such as \*), and as far as I can see they are not escaped by the bot when the user inputs one.

I would suggest to switch to html parse mode. It's less likely for users to use html tags in their polls, also python's standard library offers a basic html  escaping function to escape html tags in case sommeone need to use one in their polls

**Comment by Nukesor** [comment]
That's a good point you got there.
Markdown is really nice and convenient, but in this occasion HTML might be the proper way to do it.
Anyway it's really annoying, since this would require a rewrite of the poll interface styling and it would make translation handling way uglier, since we would either embed html in our translation files or the translations would be split into many small chunks.

The best way would probably be to escape markdown characters from user input or even better, to detect invalid markdown sequences and only escape those.

**Comment by Nukesor** [comment]
Ok. In case anyone tries to use markdown characters *_[, the bot will just return an error message, which states that the user should send messages without these characters.
