### ISSUE TITLE
Add a command to stop bot

### ISSUE THREAD

**Issue by alessiobulfaro** [Nukesor/ultimate-poll-bot#71]
Add a command to stop receiving updates from the bot and remove user id from the bot.

**Comment by Nukesor** [comment]
Wut?
Just press CTRL+C or use any service manager.

**Comment by Nukesor** [comment]
If you no longer want to receive notifications, just disable them in your user settings in the `/start` menu.

If you a special /stop command, I just added it. Just type `/stop`

Removal of user_id from the bot is not possible, since I have to track banned users. It doesn't make sense anyway, since anybody can find out your user_id in under a second.

If you want your votes removed, just click on the vote again.

If the poll is closed or deleted, than there's nothing I can do about it. This isn't something the bot (or I) can do, this is completely in the hand of the poll creator who created the poll and created the poll messages.

**Comment by Nukesor** [comment]
I'm also just implementing a option that removes your votes from active polls and deletes all of your polls.

You'll however be banned for life afterwards to prevent manipulation of votes on polls.

**Comment by Nukesor** [comment]
I also just added a `/delete_me` command.
It'll precisely show what will be deleted.
