### ISSUE TITLE
I deleted my Account

### ISSUE THREAD

**Issue by debsssss** [Nukesor/ultimate-poll-bot#78]
I clicked something by mistake and now I can’t do anything anymore. Neither create a bot nor vote in someone else’s. Is there a fix for it? 😭😭 
It says buffer/ “lädt” the whole time. 
I loved the ultimate vote bot and up until now And used it daily.

#bug @Nukesor 
![74C631FE-16DF-4602-93C3-654648579B73](https://user-images.githubusercontent.com/68853975/88540414-2c098980-d013-11ea-8c3b-2c0f26673ee1.jpeg)

**Comment by Nukesor** [comment]
Did you by step through the `/delete` command by any chance?

If you did so, you just deleted your account and won't be able to use the bot any longer.

**Comment by debsssss** [comment]
I might have. I just clicked on a couple of things to try delete something else.. 😭

Is there a possibility to change this? Can my account be reinstalled?

**Comment by Nukesor** [comment]
Nope. It's a security measure to prevent double-voting and other kinds of fraud regarding polls.
You should really read texts before randomly clicking on buttons. Especially, if they ask for your confirmation.

Solutions:
1. Get a new phone number and create a new Telegram account.
2. Host your own bot.

I won't close the issue and pin it for other people.
Especially since there are quite a few people that decide to permanently delete their account and wonder why they cannot use the bot afterwards.
